### ISSUE TITLE
Linking against psrdada requires OpenMP

### ISSUE THREAD

**Issue by ewanbarr** [MPIfR-BDG/psrdada_cpp#5]
The latest version of psrdada uses OpenMP in ipcbuf/ipcio. When building psrdada_cpp against this version of psrdada, the build fails with linker errors (unresolved OpenMP functions). There is already some OpenMP support that has been enabled in psrdada_cpp for the edd code, but this should now be made general so that if ENABLE_OPENMP=true then the `-fopenmp` flag is added by default to all builds.

**Comment by TobiasWinchen** [comment]
Closed by 87c690ea94ec8ca2e041fd806bd47e5e9a7f28d5
